corin:
    lf_q1_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lf_q1_joint
        joint_speed: 1.01
        joint_p_gain: 80
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 1
            init: 2048
            min: 848
            max: 2513

    lf_q2_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lf_q2_joint
        joint_speed: 0.52
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 2
            init: 2048
            min: 1500
            max: 2854

    lf_q3_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lf_q3_joint
        joint_speed: 1.03
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 3
            init: 2048
            min: 341
            max: 1489

    lm_q1_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lm_q1_joint
        joint_speed: 1.01
        joint_p_gain: 95
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 4
            init: 2048
            min: 1592
            max: 2513

    lm_q2_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lm_q2_joint
        joint_speed: 0.52
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 5
            init: 2048
            min: 1500
            max: 2854

    lm_q3_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lm_q3_joint
        joint_speed: 1.03
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 6
            init: 2048
            min: 341
            max: 1489

    lr_q1_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lr_q1_joint
        joint_speed: 1.01
        joint_p_gain: 95
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 7
            init: 2048
            min: 1592
            max: 3248

    lr_q2_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lr_q2_joint
        joint_speed: 0.52
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 8
            init: 2048
            min: 1500
            max: 2854

    lr_q3_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: lr_q3_joint
        joint_speed: 1.03
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 9
            init: 2048
            min: 341
            max: 1489

    rf_q1_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rf_q1_joint
        joint_speed: 1.01
        joint_p_gain: 95
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 10
            init: 2048
            min: 1592
            max: 3248

    rf_q2_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rf_q2_joint
        joint_speed: 0.52
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 11
            init: 2048
            min: 1500
            max: 2854

    rf_q3_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rf_q3_joint
        joint_speed: 1.03
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 12
            init: 2048
            min: 341
            max: 1489

    rm_q1_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rm_q1_joint
        joint_speed: 1.01
        joint_p_gain: 95
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 13
            init: 2048
            min: 1592
            max: 2513

    rm_q2_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rm_q2_joint
        joint_speed: 0.52
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 14
            init: 2048
            min: 1500
            max: 2854

    rm_q3_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rm_q3_joint
        joint_speed: 1.03
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 15
            init: 2048
            min: 341
            max: 1489

    rr_q1_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rr_q1_joint
        joint_speed: 1.03
        joint_p_gain: 95
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 16
            init: 2048
            min: 848
            max: 2513

    rr_q2_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rr_q2_joint
        joint_speed: 0.52
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 17
            init: 2048
            min: 1500
            max: 2854

    rr_q3_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: rr_q3_joint
        joint_speed: 1.03
        joint_p_gain: 70
        joint_i_gain: 0
        joint_d_gain: 50
        motor:
            id: 18
            init: 2048
            min: 341
            max: 1489