mcorin:
    # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 40  

  ##################### Joint Effort Controllers #####################
  # Leg 1 ------------------------------------------------------  
  lf_q1_controller:
    type: effort_controllers/JointEffortController
    joint: lf_q1_joint
    pid: {p: 20.001, i: 0.00000, d: 1.00}
    state_publish_rate:  50

  lf_q2_controller:
    type: effort_controllers/JointEffortController
    joint: lf_q2_joint
    pid: {p: 20.002, i: 5.00000, d: 0.00}
    state_publish_rate:  50

  lf_q3_controller:
    type: effort_controllers/JointEffortController
    joint: lf_q3_joint
    pid: {p: 15.003, i: 0.00000, d: 0.00}
    state_publish_rate:  50

  # Leg 2 ------------------------------------------------------  
  lm_q1_controller:
    type: effort_controllers/JointEffortController
    joint: lm_q1_joint
    pid: {p: 20.001, i: 0.00000, d: 1.00}
    state_publish_rate:  50

  lm_q2_controller:
    type: effort_controllers/JointEffortController
    joint: lm_q2_joint
    pid: {p: 20.002, i: 5.00000, d: 0.00}
    state_publish_rate:  50

  lm_q3_controller:
    type: effort_controllers/JointEffortController
    joint: lm_q3_joint
    pid: {p: 15.003, i: 0.00000, d: 0.00}
    state_publish_rate:  50

  # Leg 3 ------------------------------------------------------  
  lr_q1_controller:
    type: effort_controllers/JointEffortController
    joint: lr_q1_joint
    pid: {p: 20.001, i: 0.00000, d: 1.00}
    state_publish_rate:  50

  lr_q2_controller:
    type: effort_controllers/JointEffortController
    joint: lr_q2_joint
    pid: {p: 20.002, i: 5.00000, d: 0.00}
    state_publish_rate:  50

  lr_q3_controller:
    type: effort_controllers/JointEffortController
    joint: lr_q3_joint
    pid: {p: 15.003, i: 0.00000, d: 0.00}
    state_publish_rate:  50

  # Leg 4 ------------------------------------------------------  
  rf_q1_controller:
    type: effort_controllers/JointEffortController
    joint: rf_q1_joint
    pid: {p: 20.001, i: 0.00000, d: 1.00}
    state_publish_rate:  50

  rf_q2_controller:
    type: effort_controllers/JointEffortController
    joint: rf_q2_joint
    pid: {p: 20.002, i: 5.00000, d: 0.00}
    state_publish_rate:  50

  rf_q3_controller:
    type: effort_controllers/JointEffortController
    joint: rf_q3_joint
    pid: {p: 15.003, i: 0.00000, d: 0.00}
    state_publish_rate:  50

  # Leg 5 ------------------------------------------------------  
  rm_q1_controller:
    type: effort_controllers/JointEffortController
    joint: rm_q1_joint
    pid: {p: 20.001, i: 0.00000, d: 1.00}
    state_publish_rate:  50

  rm_q2_controller:
    type: effort_controllers/JointEffortController
    joint: rm_q2_joint
    pid: {p: 20.002, i: 5.00000, d: 0.00}
    state_publish_rate:  50

  rm_q3_controller:
    type: effort_controllers/JointEffortController
    joint: rm_q3_joint
    pid: {p: 15.003, i: 0.00000, d: 0.00}
    state_publish_rate:  50

  # Leg_6 ------------------------------------------------------  
  rr_q1_controller:
    type: effort_controllers/JointEffortController
    joint: rr_q1_joint
    pid: {p: 20.001, i: 0.00000, d: 1.00}
    state_publish_rate:  50

  rr_q2_controller:
    type: effort_controllers/JointEffortController
    joint: rr_q2_joint
    pid: {p: 20.002, i: 5.00000, d: 0.00}
    state_publish_rate:  50

  rr_q3_controller:
    type: effort_controllers/JointEffortController
    joint: rr_q3_joint
    pid: {p: 15.003, i: 0.00000, d: 0.00}
    state_publish_rate:  50
  ## 40 80 40
