leg_corin:
    # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  ##################### Trajectory Controllers #####################
  # Leg 1 ------------------------------------------------------  
  Leg_1_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
    - leg_1_joint_1
    - leg_1_joint_2
    - leg_1_joint_3
    gains:
      leg_1_joint_1: {p: 20.001,  i: 0.00,   d: 0.0}
      leg_1_joint_2: {p: 20.002,  i: 0.00,   d: 0.0}
      leg_1_joint_3: {p: 15.003,  i: 0.00,   d: 0.0}