<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="corin">

	<!-- The following included files set up definitions of parts of the robot body -->
	<xacro:include filename="$(find mcorin_description)/urdfs/common.xacro"/>
	<xacro:include filename="$(find mcorin_description)/urdfs/materials.xacro"/>
	<!-- Trunk -->
	<xacro:include filename="$(find mcorin_description)/urdfs/trunk/trunk_model.xacro"/>

	<!-- Legs -->
	<xacro:include filename="$(find mcorin_description)/urdfs/leg/leg.xacro"/>

	<!-- Sensors -->
	<xacro:include filename="$(find mcorin_description)/urdfs/sensors/sensors.xacro"/>

	<!-- generic simulator_gazebo plugins for starting mechanism control, ros time -->
	<xacro:include filename="$(find mcorin_description)/robots/gazebo.xacro"/>

	<!-- Now we can start using the macros included above to define the mcorin -->

	<!-- The first use of a macro. This one was defined in trunk.urdf.xacro above.
A macro like this will expand to a set of link and joint definitions, and to additional
Gazebo-related extensions (sensor plugins, etc). The macro takes an argument, name,
that equals "base", and uses it to generate names for its component links and joints
(e.g., base_link). The included origin block is also an argument to the macro. By convention,
the origin block defines where the component is w.r.t its parent (in this case the parent
is the world frame). For more, see http://www.ros.org/wiki/xacro -->


	<!-- body -->
	<!-- trunk -->
	<xacro:mCorin_trunk name="base">
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
	</xacro:mCorin_trunk>

	<xacro:mCorin_leg
		name="lf"
		parent="trunk"
		middle_leg="false"
		load_force_sensors="true">
		<origin xyz="${trunk_x/2} ${trunk_y/2} 0" rpy="0 0 ${50*PI/180}"/>
	</xacro:mCorin_leg>

	<xacro:mCorin_leg
		name="lm"
		parent="trunk"
		middle_leg="true"
		load_force_sensors="false">
		<origin xyz="0 ${trunk_y/2} 0" rpy="0 0 ${PI/2}"/>
	</xacro:mCorin_leg>

	<xacro:mCorin_leg
		name="lr"
		parent="trunk"
		middle_leg="false"
		load_force_sensors="false">
		<origin xyz="${-trunk_x/2} ${trunk_y/2} 0" rpy="0 0 ${PI/2+40*PI/180}"/>
	</xacro:mCorin_leg>

	<xacro:mCorin_leg
		name="rf"
		parent="trunk"
		middle_leg="false"
		load_force_sensors="true">
		<origin xyz="${trunk_x/2} ${-trunk_y/2} 0" rpy="0 0 ${-50*PI/180}"/>
	</xacro:mCorin_leg>

	<xacro:mCorin_leg
		name="rm"
		parent="trunk"
		middle_leg="true"
		load_force_sensors="false">
		<origin xyz="0 ${-trunk_y/2} 0" rpy="0 0 ${-PI/2}"/>
	</xacro:mCorin_leg>

	<xacro:mCorin_leg
		name="rr"
		parent="trunk"
		middle_leg="false"
		load_force_sensors="false">
		<origin xyz="${-trunk_x/2} ${-trunk_y/2} 0" rpy="0 0 ${-PI/2-40*PI/180}"/>
	</xacro:mCorin_leg>

	<!-- Sensors -->
	<xacro:IMU
		parent="trunk"
		imu_name="trunk_imu"
		imu_topic="middle/data"
		imu_service="trunk/service"
		update_rate="100">
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
	</xacro:IMU>

	<xacro:IMU
		parent="trunk"
		imu_name="trunk_offset_imu"
		imu_topic="offset/data"
		imu_service="trunk/service2"
		update_rate="100">
		<origin xyz="0.0 0.0 0.022" rpy="0 0 0"/>
	</xacro:IMU>

	<xacro:LIDAR
		parent="trunk"
		lidar_name="trunk_lidar"
		lidar_topic="lidar/data"
		update_rate="100">
		<origin xyz="0.06 0.0 0.04" rpy="0 0 ${PI/2}"/>
	</xacro:LIDAR>

</robot>
