#!/usr/bin/env python

## Script to move robot joints into a position
## the position is not held unless physics engine is paused

import rospy, sys, os, time
import string
import warnings
import tf
from math import pi

from gazebo_msgs.srv import *
from std_srvs.srv import Empty
from gazebo_msgs.msg import ModelState
from geometry_msgs.msg import Pose
from geometry_msgs.msg import Twist

def deg2rad(q):
	return (q*pi/180)

if __name__ == "__main__":
	if len(sys.argv) < 2:
		sleep_time = 0.0
	else:
		print sys.argv[1]
		sleep_time = float(sys.argv[1])

	# Define variables
	model_state = ModelState()
	pose  		= Pose()
	twist 		= Twist()

	model_name 		= 'corin'
	reference_frame	= 'world'
	
	pose.position.x		= 0.5
	pose.position.y		= -1.0
	pose.position.z		= 0.2
	roll 				= 0.0
	pitch 				= 0.0
	yaw 				= 0.0
	quaternion 			= tf.transformations.quaternion_from_euler(deg2rad(roll), deg2rad(pitch), deg2rad(yaw))
	pose.orientation.x	= quaternion[0]
	pose.orientation.y	= quaternion[1]
	pose.orientation.z	= quaternion[2]
	pose.orientation.w	= quaternion[3]

	model_state.model_name 		= model_name
	model_state.pose 			= pose
	model_state.reference_frame = reference_frame

	gazebo_namespace = '/gazebo'
	rospy.wait_for_service('%s/set_model_state'%(gazebo_namespace))
	rospy.sleep(sleep_time)

	try:
		set_model_state = rospy.ServiceProxy('%s/set_model_state'%(gazebo_namespace), SetModelState)
		rospy.loginfo("Calling service %s/set_model_state"%gazebo_namespace)
		resp = set_model_state(model_state)
		rospy.loginfo("Set model state status: %s"%resp.status_message)
		print resp.status_message

	except rospy.ServiceException as e:
		print("Service call failed: %s" % e)
