lf_q1_joint :   # MX-64
   return_delay_time     : 0    # item name : value
   operating_mode        : 3    # 0: current; 1: velocity; 3: position; 5: current base position; 20: pwm
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 2700   #  57.3 deg
   min_position_limit    : 1396   # -57.3 deg
   velocity_limit        : 150
   goal_position         : 2048   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50    # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lf_q2_joint :   # MX-64
   return_delay_time     : 03500
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3500   #  127 deg
   min_position_limit    : 596    # -127 deg
   velocity_limit        : 150
   goal_position         : 3500   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lf_q3_joint :   # MX-64
   return_delay_time     : 0
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3868   #  160 deg
   min_position_limit    : 230    # -160 deg
   velocity_limit        : 150
   goal_position         : 228   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lm_q1_joint :   # MX-64
   return_delay_time     : 0    # item name : value
   operating_mode        : 3    # 0: current; 1: velocity; 3: position; 5: current base position; 20: pwm
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 2594   #  48 deg
   min_position_limit    : 1502   # -48 deg
   velocity_limit        : 150
   goal_position         : 2048   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lm_q2_joint :   # MX-64
   return_delay_time     : 03500
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3500   #  127 deg
   min_position_limit    : 596    # -127 deg
   velocity_limit        : 150
   goal_position         : 3500   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lm_q3_joint :   # MX-64
   return_delay_time     : 0
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3868   #  160 deg
   min_position_limit    : 228    # -160 deg
   velocity_limit        : 150
   goal_position         : 230   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lr_q1_joint :   # MX-64
   return_delay_time     : 0    # item name : value
   operating_mode        : 3    # 0: current; 1: velocity; 3: position; 5: current base position; 20: pwm
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 2685   #  56.0 deg
   min_position_limit    : 1396   # -57.3 deg
   velocity_limit        : 150
   goal_position         : 2048   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50    # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lr_q2_joint :   # MX-64
   return_delay_time     : 03500
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3500   #  127 deg
   min_position_limit    : 596    # -127 deg
   velocity_limit        : 150
   goal_position         : 3500   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

lr_q3_joint :   # MX-64
   return_delay_time     : 0
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3868   #  160 deg
   min_position_limit    : 228    # -160 deg
   velocity_limit        : 150
   goal_position         : 230   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rf_q1_joint :   # MX-64
   return_delay_time     : 0    # item name : value
   operating_mode        : 3    # 0: current; 1: velocity; 3: position; 5: current base position; 20: pwm
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 2700   #  57.3 deg
   min_position_limit    : 1396   # -57.3 deg
   velocity_limit        : 150
   goal_position         : 2048   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50    # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rf_q2_joint :   # MX-64
   return_delay_time     : 03500
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3500   #  127 deg
   min_position_limit    : 596    # -127 deg
   velocity_limit        : 150
   goal_position         : 3500   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rf_q3_joint :   # MX-64
   return_delay_time     : 0
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3868   #  160 deg
   min_position_limit    : 228    # -160 deg
   velocity_limit        : 150
   goal_position         : 230   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rm_q1_joint :   # MX-64
   return_delay_time     : 0    # item name : value
   operating_mode        : 3    # 0: current; 1: velocity; 3: position; 5: current base position; 20: pwm
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 2594   #  48 deg
   min_position_limit    : 1502   # -48 deg
   velocity_limit        : 150
   goal_position         : 2048   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50    # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rm_q2_joint :   # MX-64
   return_delay_time     : 03500
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3500   #  127 deg
   min_position_limit    : 596    # -127 deg
   velocity_limit        : 150
   goal_position         : 3500   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rm_q3_joint :   # MX-64
   return_delay_time     : 0
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3868   #  160 deg
   min_position_limit    : 228    # -160 deg
   velocity_limit        : 150
   goal_position         : 230   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rr_q1_joint :   # MX-64
   return_delay_time     : 0    # item name : value
   operating_mode        : 3    # 0: current; 1: velocity; 3: position; 5: current base position; 20: pwm
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 2685   #  56.0 deg
   min_position_limit    : 1411   # -56.0 deg
   velocity_limit        : 150
   goal_position         : 2048   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50    # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rr_q2_joint :   # MX-64
   return_delay_time     : 03500
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3500   #  127 deg
   min_position_limit    : 596    # -127 deg
   velocity_limit        : 150
   goal_position         : 3500   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0

rr_q3_joint :   # MX-64
   return_delay_time     : 0
   operating_mode        : 3
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 3868   #  160 deg
   min_position_limit    : 228    # -160 deg
   velocity_limit        : 150    # 3.6 rad/s
   goal_position         : 230   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50   # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 10
   profile_acceleration  : 0
