offset:
  lf_q1: 0
  lf_q2: 0
  lf_q3: 0
  lm_q1: 0
  lm_q2: 0
  lm_q3: 0
  lr_q1: 0
  lr_q2: 0
  lr_q3: 0
  rf_q1: 0
  rf_q2: 0
  rf_q3: 0
  rm_q1: 0
  rm_q2: 0
  rm_q3: 0
  rr_q1: 0
  rr_q2: 0
  rr_q3: 0
init_pose_for_offset_tuner:
  lf_q1: 0
  lf_q2: 0
  lf_q3: 0
  lm_q1: 0
  lm_q2: 0
  lm_q3: 0
  lr_q1: 0
  lr_q2: 0
  lr_q3: 0
  rf_q1: 0
  rf_q2: 0
  rf_q3: 0
  rm_q1: 0
  rm_q2: 0
  rm_q3: 0
  rr_q1: 0
  rr_q2: 0
  rr_q3: 0
